---
title: "Discussion"
author: "Kushal K Dey & Hussein Al-Asadi"
date: "September 14, 2015"
output: html_document
---

From the real data analysis, we have two major concerns

## (1) ancient frequencies driven away from true ancient frequency.

In the real data analysis of model 2, section K_known = 3 & K_unknown = 0, we saw that the Yamanaya (for example) did not cluster exclusively with their estimated allele frequency. This is counter to our expectation that the Yamanaya should be mainly composed of the Yamamaya estimated frequency. A possible explanation to this problem is that the Yamanaya frequency is driven to another population frequency (which is unknown) that better fits the modern data. 

To illustrate this, we simulate a model in which individuals come from three ancestries A1 at 78%, A2 at 20%, and A3 at 2%, and we only have the frequency of A2 with number of samples = 100, and A3 with number of samples = 10. 

```{r, echo=FALSE, results='hide'}
setwd('/Users/kushal/Documents/ancient-structure/src')
source('ancient_structure.R');

sim_example <- function(fa1, fa2, fa3, nsamp, nSNPs){
  # nsamp is a vector of length 3
  fall = rbind(fa1, fa2, fa3);
  counts_data <- matrix(nrow = 0, ncol = nSNPs)
  for(n in 1:3)
  {
    counts_data = rbind(counts_data,do.call(cbind, lapply(1:nSNPs,function(x) rbinom(nsamp[n], 2, prob = fall[n,x]))))
  }
  
  return(counts_data)
}

nSNPs = 100
fa2 = runif(n = nSNPs)
fa3 = runif(n = nSNPs)
fa1 = 0.5*runif(n = nSNPs) + 0.5*fa3

nsamp <- c(390, 100,10);

data <- sim_example(fa1, fa2, fa3, nsamp = nsamp, nSNPs=nSNPs)
npop <- 3
pop_labs <- unlist(lapply(1:npop, function(n) rep(toString(n),nsamp[n])));
source_labs <- c(toString(2), toString(3));

K_unknown = 3
freq_mat = as.matrix(rbind(fa2, fa3))
n_obs = c(100,10);

#f_obs <- matrix(0,nrow=nSNPs, ncol=K_known);
#for (k in 1:K_known){
#  f_obs[,k] = rbinom(nSNPs,2*n_obs[k], freq_mat[,k])/(2*n_obs[k])
#}
out <- ancient_structure(geno_data = data, K_unknown = K_unknown, pop_labs =pop_labs, source_labs=NULL, max_iter = 10000)
K_pooled <- K_unknown
barplot(t(out$q),col=2:(K_pooled+1),axisnames=F,space=0,border=NA,main=paste("estd structure: No. of clusters=",K_pooled),
        las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

q = rbind(matrix(rep(c(1,0,0),390),nrow=390,byrow=TRUE), matrix(rep(c(0,1,0),100),nrow=100,byrow=TRUE),matrix(rep(c(0,0,1),10),nrow=10,byrow=TRUE))

barplot(t(q),col=c(3,2,4),axisnames=F,space=0,border=NA,main=paste("true structure: No. of clusters=",K_pooled),
        las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

```

## (2) When is another source population necessary?

We simulated genotype data under the W-F model for two clusters and fitted 3 clusters (therefore one is un-necessary), and we saw that individuals showed significant ancestry from this third un-necessary cluster. However, this third cluster did not show and discernable pattern and looked like noise. Therefore, it makes it difficult to distinguish between truly biological clusters and noise.

## (3) drift
We simulated under drift and found that it was not really affecting cluster membership, however, we did not explore the entire space of possibilities. For example, we set the population size to be 10,000 and bottlenecks can magnify drift in real data as observed by this [paper](http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1005397)

## (4) contamination

Ancient DNA is contaminated with modern dna. 
