---
title: 'Exploratory analysis of ancient data'
author: "Kushal K Dey, Hussein Al asadi"
date: "August 7, 2015"
output: html_document
---

## General admixture analysis 

We used the [software](https://www.genetics.ucla.edu/software/admixture/) by David Alexander (UCLA).

```{r admix, echo=FALSE, eval=TRUE}
library(data.table)
data.clst <- read.csv('data.clst', stringsAsFactors = FALSE, header=FALSE, sep = "\t");
data.fam <- read.table('haak_fig3_set.fam');

pop_ids <- data.clst[match(data.fam$V2, data.clst$V2),3]


plot_admixture <- function(K, pop_ids)
{
  P_data <- data.frame(fread(paste0('Admixture/haak_fig3_set.',K,'.P')));
  Q_data <- data.frame(fread(paste0('Admixture/haak_fig3_set.',K,'.Q')))
  Q_data_pop <- sapply(1:K, function(num) tapply(Q_data[,num], pop_ids,mean));

  ancient_pop <- unique(pop_ids)[24:44];
  modern_pop <- unique(pop_ids)[1:23];

  Q_data_pop_ancient <- Q_data_pop[match(ancient_pop,rownames(Q_data_pop)),];
  Q_data_pop_modern <-  Q_data_pop[-match(ancient_pop,rownames(Q_data_pop)),];

  barplot(t(Q_data_pop_ancient),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("Ancient data: No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
  abline(v=1:length(ancient_pop))
  mid_point =seq(0.5,dim(Q_data_pop_ancient)[1]-0.5,length.out=dim(Q_data_pop_ancient)[1]);
  axis(1,at=mid_point, ancient_pop,las=2,cex.axis=0.5);

  barplot(t(Q_data_pop_modern),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("Modern data: No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
  abline(v=1:length(modern_pop))
  mid_point =seq(0.5,dim(Q_data_pop_modern)[1]-0.5,length.out=dim(Q_data_pop_modern)[1]);
  axis(1,at=mid_point, modern_pop,las=2,cex.axis=0.5);

}
```

### K=3 

```{r ancient_admixture_3, echo=FALSE, eval=TRUE, cache=TRUE}
plot_admixture(3,pop_ids)
```

### K=5

```{r ancient_admixture_5, echo=FALSE, eval=TRUE, cache=TRUE}
plot_admixture(5,pop_ids)
```

### K=7 

```{r ancient_admixture_7, echo=FALSE, eval=TRUE, cache=TRUE}
plot_admixture(7,pop_ids)
```


## PCA

```{r pca, echo=FALSE, eval=TRUE}

pca_eigenvalues <- data.frame(read.table('PCA/pca_eigenvalues.txt'));
pca_eigenvectors <- data.frame(fread('PCA/pca_eigenvectors.txt'), row.names=TRUE);

plot_pc <- function(lab1,lab2)
{
  eigen1 = as.numeric(pca_eigenvectors[,lab1])
  eigen2 = as.numeric(pca_eigenvectors[,lab2])
  plot(0, xlim = c(min(eigen1), max(eigen1)), ylim = c(min(eigen2), max(eigen2)),xlab=paste0("PC   ",lab1),ylab=paste0("PC ",lab2));
  text(eigen1, eigen2 ,pop_ids,cex=0.5)
}

plot_pc(1,2)
plot_pc(1,3)
plot_pc(2,3)


```

## Treemix

```{r treemix, echo=TRUE, eval=FALSE}
source("Treemix/plotting_funcs.R")
plot_tree("Treemix/out_stem")
```

