---
title: "simulations_w_drift"
output: html_document
---


```{r, echo = FALSE, cache=TRUE}
######## LOAD FUNCTIONS  #######

rm(list = ls())
library('data.table')
source('ancient_structure.R');

# Simulate under W-F model
sim_drift<-function(N=40, p0=.2,ngen=100, nSNPs = 1){
  pvec = numeric(nSNPs)
  pvec = p0 	 
  for( i in 2:ngen){
    pvec = rbinom(nSNPs,2*N,pvec)/(2*N)
  }
  return( pvec )
}

# Simulate under a specific model of ancient admixture
#fa1  --(t1)--->   fb1                              ---(t2)--->  fc1
#                  fb2 = alpha*fb1 = (1-alpha)*fb2  ---(t2)--->  fc2
#fa2  --(t1)--->   fb3                              ---(t2)--->  fc3
# then data is returned in which genotype data is simulated from fc1, fc2, fc3 respectively.
# Therefore data is (nsamp)*3 by 3
sim_ancient_admix <- function(fa1, fa2, t1, t2, alpha, N, nsamp){
  nSNPs <- length(fa1)
  fb1 = sim_drift(p0 = fa1, ngen = t1, N = N, nSNPs = nSNPs)
  fb3 = sim_drift(p0 = fa2, ngen = t1, N = N, nSNPs = nSNPs) 
  fb2 = alpha*fb1 + (1-alpha)*fb3
  
  fc1 = sim_drift(p0 = fb1, ngen = t2, N = N, nSNPs = nSNPs)
  fc2 = sim_drift(p0 = fb2, ngen = t2, N = N, nSNPs = nSNPs)
  fc3 = sim_drift(p0 = fb3, ngen = t2, N = N, nSNPs = nSNPs)
  
  fall = rbind(fc1, fc2, fc3);
  counts_data <- matrix(nrow = 0, ncol = nSNPs)
  for(n in 1:3)
  {
    counts_data = rbind(counts_data,do.call(cbind, lapply(1:nSNPs,function(x) rbinom(nsamp, 2, prob = fall[n,x]))))
  }
  
  return(counts_data)
}

removeDup <- function(M){
  # M is nrow = nclusters, ncol = nSNPs
  # to remove all duplicate cols but too slow: dataf[sapply(dataf, function(x) length(unique(x))>1)]
  inter0 = (M[1,] == 0)
  inter = (M[1,] == 1)
  for (i in 2:nrow(M)){
    inter0 = inter0 & (M[i,] == 0)
    inter = inter & (M[i,] == 1)
  }
  return(as.numeric(unique(c(which(inter == TRUE), which(inter0 == TRUE)))))
}
```

```{r, echo=FALSE, cache=TRUE}
########### SET UP DATA ############

nSNPs = 10000

#fa1 = runif(nSNPs)
#fa2 = runif(nSNPs)
#fa2 = 0.95*fa1 + 0.05*runif(nSNPs, 0, 0.1)

a_freq <- as.matrix(data.frame(fread("../external_data/ancestral_freqs.txt"), row.names = TRUE));
a_freq <- a_freq[1:2,-removeDup(a_freq)]
a_freq <- a_freq[,1:nSNPs]
fa1 = as.numeric(a_freq[1,])
fa2 = as.numeric(a_freq[2,])
```


```{r}
t1 = 100
t2 = 100
alpha = 0.5
nsamp = 100
N = 1e4

#snpsToRemove = unique(c(which(fa2 > 0.999 | fa2 < 0.001), which(fa1 > 0.999 | fa1 < 0.001)))
#fa1 = fa1[-snpsToRemove]
#fa2 = fa2[-snpsToRemove]
data = sim_ancient_admix(fa1, fa2, t1, t2, alpha, N, nsamp)

K_known = 2
K_unknown = 0
K_pooled = K_known + K_unknown
freq_mat = as.matrix(rbind(fa1, fa2))
out <- ancient_structure(geno_data = data, f_known = t(freq_mat), K_unknown = K_unknown, max_iter = 100)
barplot(t(out$q),col=2:(K_pooled+1),axisnames=F,space=0,border=NA,main=paste("estd structure: No. of clusters=",K_pooled),
        las=1,ylim=c(0,1),cex.axis=1.5,cex.main=1.4)

```