---
title: 'Haak Human Origins data analysis: Model 2'
author: "Kushal K Dey, Hussein Al Asadi"
date: "September 14, 2015"
output: html_document
---

We present the results of fitting ancient Sructure (Model 2) on Haak Human Origins on a total of 403 samples and around 300,000 SNPs. We ran two set ups 

### K_Known=3   K_Unknown=0

```{r known_3_unknown_0, echo=FALSE, eval=TRUE, results='hide'}
setwd('/Users/kushal/Documents/ancient-structure/src')
library(data.table)
data.clst <- read.csv('../exploratory/data.clst', stringsAsFactors = FALSE, header=FALSE, sep = "\t");
data.fam <- read.table('../exploratory/haak_fig3_set.fam');

pop_ids <- data.clst[match(data.fam$V2, data.clst$V2),3]

Q_data <- as.matrix(read.table("../internal_data/sample_correction/q_known_3_unknown_0.txt"));
#Q_data <- as.matrix(read.table("../exploratory/Admixture/haak_fig3_set.5.Q"))

modern_Q <- Q_data[1:331,];
ancient_Q <- Q_data[-(1:331),];

pop_ids_modern <- pop_ids[1:331];
K=dim(modern_Q)[2];
barplot(t(modern_Q),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);

labels = match(unique(pop_ids_modern), pop_ids_modern);
abline(v=labels-1,lwd=2)

labels_low=labels-1;
labels_up=c(labels_low[2:length(labels_low)],dim(modern_Q)[1]);
mid_point <- labels_low +0.5*(labels_up-labels_low);
axis(1,at=mid_point, unique(pop_ids_modern),las=2,cex.axis=0.5);


pop_ids_ancient <- pop_ids[-(1:331)];
K=dim(ancient_Q)[2];
barplot(t(ancient_Q),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);

labels = match(unique(pop_ids_ancient), pop_ids_ancient);
abline(v=labels-1,lwd=2)

labels_low=labels-1;
labels_up=c(labels_low[2:length(labels_low)],dim(ancient_Q)[1]);
mid_point <- labels_low +0.5*(labels_up-labels_low);
axis(1,at=mid_point, unique(pop_ids_ancient),las=2,cex.axis=0.5);



Q_data_pop <- sapply(1:K, function(num) tapply(Q_data[,num], pop_ids,mean));

ancient_pop <- unique(pop_ids)[24:44];
modern_pop <- unique(pop_ids)[1:23];

Q_data_pop_ancient <- Q_data_pop[match(ancient_pop,rownames(Q_data_pop)),];
Q_data_pop_modern <-  Q_data_pop[-match(ancient_pop,rownames(Q_data_pop)),];

barplot(t(Q_data_pop_ancient),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
abline(v=1:length(ancient_pop))
mid_point =seq(0.5,dim(Q_data_pop_ancient)[1]-0.5,length.out=dim(Q_data_pop_ancient)[1]);
axis(1,at=mid_point, ancient_pop,las=2,cex.axis=0.5);

barplot(t(Q_data_pop_modern),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
abline(v=1:length(modern_pop))
mid_point =seq(0.5,dim(Q_data_pop_modern)[1]-0.5,length.out=dim(Q_data_pop_modern)[1]);
axis(1,at=mid_point, modern_pop,las=2,cex.axis=0.5);
```

### K_Known=3   K_Unknown=1

```{r known_3_unknown_1, echo=FALSE, eval=TRUE, results='hide'}
setwd('/Users/kushal/Documents/ancient-structure/src')
library(data.table)
data.clst <- read.csv('../exploratory/data.clst', stringsAsFactors = FALSE, header=FALSE, sep = "\t");
data.fam <- read.table('../exploratory/haak_fig3_set.fam');

pop_ids <- data.clst[match(data.fam$V2, data.clst$V2),3]

Q_data <- as.matrix(read.table("../internal_data/sample_correction/q_known_3_unknown_1.txt"));
#Q_data <- as.matrix(read.table("../exploratory/Admixture/haak_fig3_set.5.Q"))

modern_Q <- Q_data[1:331,];
ancient_Q <- Q_data[-(1:331),];

pop_ids_modern <- pop_ids[1:331];
K=dim(modern_Q)[2];
barplot(t(modern_Q),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);

labels = match(unique(pop_ids_modern), pop_ids_modern);
abline(v=labels-1,lwd=2)

labels_low=labels-1;
labels_up=c(labels_low[2:length(labels_low)],dim(modern_Q)[1]);
mid_point <- labels_low +0.5*(labels_up-labels_low);
axis(1,at=mid_point, unique(pop_ids_modern),las=2,cex.axis=0.5);


pop_ids_ancient <- pop_ids[-(1:331)];
K=dim(ancient_Q)[2];
barplot(t(ancient_Q),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);

labels = match(unique(pop_ids_ancient), pop_ids_ancient);
abline(v=labels-1,lwd=2)

labels_low=labels-1;
labels_up=c(labels_low[2:length(labels_low)],dim(ancient_Q)[1]);
mid_point <- labels_low +0.5*(labels_up-labels_low);
axis(1,at=mid_point, unique(pop_ids_ancient),las=2,cex.axis=0.5);



Q_data_pop <- sapply(1:K, function(num) tapply(Q_data[,num], pop_ids,mean));

ancient_pop <- unique(pop_ids)[24:44];
modern_pop <- unique(pop_ids)[1:23];

Q_data_pop_ancient <- Q_data_pop[match(ancient_pop,rownames(Q_data_pop)),];
Q_data_pop_modern <-  Q_data_pop[-match(ancient_pop,rownames(Q_data_pop)),];

barplot(t(Q_data_pop_ancient),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
abline(v=1:length(ancient_pop))
mid_point =seq(0.5,dim(Q_data_pop_ancient)[1]-0.5,length.out=dim(Q_data_pop_ancient)[1]);
axis(1,at=mid_point, ancient_pop,las=2,cex.axis=0.5);

barplot(t(Q_data_pop_modern),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
abline(v=1:length(modern_pop))
mid_point =seq(0.5,dim(Q_data_pop_modern)[1]-0.5,length.out=dim(Q_data_pop_modern)[1]);
axis(1,at=mid_point, modern_pop,las=2,cex.axis=0.5);
```


### K_Known=3   K_Unknown=2

```{r known_3_unknown_2, echo=FALSE, eval=TRUE, results='hide'}
setwd('/Users/kushal/Documents/ancient-structure/src')
library(data.table)
data.clst <- read.csv('../exploratory/data.clst', stringsAsFactors = FALSE, header=FALSE, sep = "\t");
data.fam <- read.table('../exploratory/haak_fig3_set.fam');

pop_ids <- data.clst[match(data.fam$V2, data.clst$V2),3]

Q_data <- as.matrix(read.table("../internal_data/sample_correction/q_known_3_unknown_2.txt"));
#Q_data <- as.matrix(read.table("../exploratory/Admixture/haak_fig3_set.5.Q"))

modern_Q <- Q_data[1:331,];
ancient_Q <- Q_data[-(1:331),];

pop_ids_modern <- pop_ids[1:331];
K=dim(modern_Q)[2];
barplot(t(modern_Q),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);

labels = match(unique(pop_ids_modern), pop_ids_modern);
abline(v=labels-1,lwd=2)

labels_low=labels-1;
labels_up=c(labels_low[2:length(labels_low)],dim(modern_Q)[1]);
mid_point <- labels_low +0.5*(labels_up-labels_low);
axis(1,at=mid_point, unique(pop_ids_modern),las=2,cex.axis=0.5);


pop_ids_ancient <- pop_ids[-(1:331)];
K=dim(ancient_Q)[2];
barplot(t(ancient_Q),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);

labels = match(unique(pop_ids_ancient), pop_ids_ancient);
abline(v=labels-1,lwd=2)

labels_low=labels-1;
labels_up=c(labels_low[2:length(labels_low)],dim(ancient_Q)[1]);
mid_point <- labels_low +0.5*(labels_up-labels_low);
axis(1,at=mid_point, unique(pop_ids_ancient),las=2,cex.axis=0.5);



Q_data_pop <- sapply(1:K, function(num) tapply(Q_data[,num], pop_ids,mean));

ancient_pop <- unique(pop_ids)[24:44];
modern_pop <- unique(pop_ids)[1:23];

Q_data_pop_ancient <- Q_data_pop[match(ancient_pop,rownames(Q_data_pop)),];
Q_data_pop_modern <-  Q_data_pop[-match(ancient_pop,rownames(Q_data_pop)),];

barplot(t(Q_data_pop_ancient),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
abline(v=1:length(ancient_pop))
mid_point =seq(0.5,dim(Q_data_pop_ancient)[1]-0.5,length.out=dim(Q_data_pop_ancient)[1]);
axis(1,at=mid_point, ancient_pop,las=2,cex.axis=0.5);

barplot(t(Q_data_pop_modern),col=2:(K+1),axisnames=F,space=0,border=NA,main=paste("No. of clusters=",K),las=1,ylim=c(0,1),cex.axis=0.5,cex.main=1.4);
abline(v=1:length(modern_pop))
mid_point =seq(0.5,dim(Q_data_pop_modern)[1]-0.5,length.out=dim(Q_data_pop_modern)[1]);
axis(1,at=mid_point, modern_pop,las=2,cex.axis=0.5);
```

